Use `TestEngine` to initialize Open Telemetry wrapper
Switch from a `TestExecutionListener` to a `TestEngine` to trigger
the addition of the Open Telemetry wrapper. This update prevents a
`NoClassDefFoundError` from being raise by Gradle 7 since unlike
`TestExecutionListener`, the `TestEngine` is available on the test
classpath.

Closes gh-